### ISSUE TITLE
Issue in events.patch

### ISSUE THREAD

**Issue by prasadKodeInCloud** [wanasit/google-calendar#16]
Request type in events.patch method should be changed to 'PATCH' which is mistaken as 'POST'
Corrected code is in here
https://github.com/prasadKodeInCloud/google-calendar/blob/master/GoogleCalendar.js#L279

**Comment by wanasit** [comment]
Thanks for pointing out. Fixed. 
(Next time, when you found a small bug like this, I suggest creating a Pull Request instead of Issue)

**Comment by prasadKodeInCloud** [comment]
Sure. will do next time. would be grateful if you can publish the changes.
Thanks !

On Mon, Jan 12, 2015 at 12:06 PM, Wanasit Tanakitrungruang <
notifications@github.com> wrote:

> Thanks for pointing out. Fixed.
> (Next time, when you found a small bug like this, I suggest creating a
> Pull Request instead of Issue)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/wanasit/google-calendar/issues/16#issuecomment-69533903
> .

## 

Best Regards
Prasad

*Reality is a projection of the mind *
                                      - (Buddha)
