### ISSUE TITLE
Calendar insert

### ISSUE THREAD

**Issue by krthr** [wanasit/google-calendar#24]
I need help :c I don't know how to use the insert method in calendars module

**Comment by phulsechinmay** [comment]
This might be a bit late, but here's how I did it:

``` JS
calendar = {
    summary: 'TestCalendar',
    timeZone: 'America/Chicago'
}

gcal(accessToken).calendars.insert(calendar, (err, data) => {
   // Do whatever you want with the data here
}
```

You can add more data to the _calendar_ object by following the style given [here](https://developers.google.com/calendar/v3/reference/calendars#resource)

**Comment by krthr** [comment]
Danke! google-calendar is awesome 🆒
